services:
  ryndor-character-maker:
    build: .
    container_name: ryndor-character-maker
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    restart: unless-stopped
